#!/usr/bin/env bash

# Simple stand-alone wrapper for rofi-power-menu.
#
# This script takes the same CLI arguments as rofi-power-menu.
#
# rofi-script-to-dmenu needs to be installed

# Use local rofi-power-menu if present. This makes developing easier.
command systemctl start httpd
command systemctl start mariadb
echo "start services"